### PR TITLE
Make the copy option more functional.

### PR DESCRIPTION
**Pull request by Chayandev**
### Fixed Issue no :- #3 

Hay @jatiinyadav I have fixed the issue #3, which I have raised. 

**Here are the Changes  -**

Screenshot 2023-10-08 204344

_When hovering on the color code 'copy' text will be visible, but when copy is clicked this change 'copied' will be visible, this will make user confirmed that the color code is copied successfully._

### CODE REVIEW

**Comment by jatiinyadav** [comment]
Hi @Chayandev, Thankyou for your contribution.
I would like to suggest some changes:-

- Please remove the Check mark icon.
- It would be great if you add a popup (as you have mentioned in the issue) at the top right corner with text : 
`Copied {color_code}!!`
- Make sure that the popup disappears after 2 seconds.

**Comment by Chayandev** [comment]
Ok sure ...

**Comment by Chayandev** [comment]
hay @jatiinyadav I fixed the code according to your proposal.

**Here the changes :**

Screenshot 2023-10-08 222103

**Comment by jatiinyadav** [comment]
@Chayandev Thankyou for your valuable contribution.

**Pull request merged**
